-
  name: csg-assignment
  hosts: gcp-vm
  become: true
  vars:
    token_key: "CSG_$h4p3#7e"
  tasks:
    - name: Create a directory
      file:
        path: /opt/csg_security_agent
        state: directory
        mode: '744'
        owner: ansible
    - name: Copy script file to vm
      copy:
        src: security_agent_installer_linux_amd64_v1.0.0.sh
        dest: /opt/csg_security_agent/security_agent_installer.sh
        mode: '744'
        owner: ansible
    - name: Copy config file to vm
      template:
        src: security_agent_config.conf
        dest: /opt/csg_security_agent/security_agent_config.conf
    - name: Execute the script
      command: bash /opt/csg_security_agent/security_agent_installer.sh --config /opt/csg_security_agent/security_agent_config.conf --token {{ token_key }}

